### ISSUE TITLE
Icon: Add new custom 'lightbulb' icon

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1026]
- [ ] Add svg to custom icons dir
- [ ] Register the new icon in the TsIconComponent constructor
- [ ] Add new icon to the doc

![icon-lightbulb.svg](https://images.zenhubusercontent.com/59fa074d8a75884b9085aa07/ab31527f-21fe-49a3-8a6a-ee8a41cd5f42)

**Comment by benjamincharity** [comment]
Waiting on SVG resource

**Comment by lildziner** [comment]
Hey Ben, circling back to this icon. 
[icon-lightbulb.svg.zip](https://github.com/GetTerminus/terminus-ui/files/2429251/icon-lightbulb.svg.zip)

**Comment by shani-terminus** [comment]
I made some edits to the svg, removing the fill and polygon. These edits allow the lightbulb to accept theme attribute.
