### ISSUE TITLE
Terminus Engage Navigation Bar 

### ISSUE THREAD

**Issue by sunbuns** [GetTerminus/terminus-ui#1050]
New feature. 

Multiple Engagement Models is scheduled to be released in Q4 and we need a way for users to be able to access the model creation page directly from the nav bar in Terminus Engage (MyT) without having to go to the Site Visits link then click to the Engagement Model Setup page. If we keep our current nav bar, having the ability to have a drop down per main link would help the user get where they need to without having to click into a page first. 

There has also been talk about creating a new navigation bar that will be iframed in both products: Terminus Engage and Terminus Hub (formerly Brightfunnel) so there is a consistent experience between both products.

**Comment by sunbuns** [comment]
@benjamincharity I added text in the body of the issue submitted, did it not come over?

**Comment by benjamincharity** [comment]
Hmm not seeing it :/

![screen shot 2018-09-10 at 4 04 19 pm](https://user-images.githubusercontent.com/270193/45321384-3d2a7980-b513-11e8-9139-d50a8b9d3b05.png)

**Comment by sunbuns** [comment]
Why is happening to me? This is what I see in the body of the description but when I save, nothing shows up. 
<img width="684" alt="nav bar" src="https://user-images.githubusercontent.com/19916526/45556878-5761a180-b80a-11e8-9454-97bccb334bf9.png">

**Comment by benjamincharity** [comment]
The `<!--` is the beginning of an HTML comment. It's used so that the helper text isn't actually output as issue comment (that way we don't have to delete that text from every single issue).

I just removed those comments and it's showing now :)

**Comment by benjamincharity** [comment]
> need a way for users to be able to access the model creation page directly from the nav bar in Terminus Engage (MyT) without having to go to the Site Visits link then click to the Engagement Model Setup page.

This should already be supported. Core has full control over what links appear in the navigation.

> been talk about creating a new navigation bar that will be iframed in both products

When you say 'new', is there missing functionality?

**Comment by benjamincharity** [comment]
Closing as inactive
