### ISSUE TITLE
Icon: Add new custom 'csv' icon

### ISSUE THREAD

**Issue by lildziner** [GetTerminus/terminus-ui#1078]
We created a new csv icon for the wizard. In the mockup you'll see a unique export of it was created to match the logo svgs.  Attaching the master icon to match our baseline 24px material icons in the library. 
![image](https://user-images.githubusercontent.com/4960080/46226298-dcc87400-c329-11e8-9fef-3183a848abf9.png)
[icon-csv.svg.zip](https://github.com/GetTerminus/terminus-ui/files/2429263/icon-csv.svg.zip)

---

- [ ] Add icon
  - [ ] Verify the icon is visually consistent with existing material icons
- [ ] Add docs

**Comment by benjamincharity** [comment]
@lildziner thanks for opening this up!

I notice this icon has a different visual weight than our current icon set. Is there some sort of rule-set or boundary as to what custom icons can be used in what context? For instance, in the above image it looks fine, but if we were to place it next to some existing Material icons it would look like it's from a different icon set.

**Comment by benjamincharity** [comment]
Related icon needs:

- https://github.com/GetTerminus/terminus-ui/issues/1026
- https://github.com/GetTerminus/terminus-ui/issues/1047
