### ISSUE TITLE
Icon: Toggling two icons isn't working correctly

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1090]
Causing the mat-ripple to appear in the wrong spot:

![bug](https://user-images.githubusercontent.com/270193/47528194-868c1980-d872-11e8-9dcc-1b73d1cfde17.gif)

---

- [ ] Need to verify that this is still happening

**Comment by benjamincharity** [comment]
@edwin-terminus do you happen to know if this bug still present?

**Comment by edwin-terminus** [comment]
The animation issue no longer reproducible.  Please close.
