### ISSUE TITLE
CSV Entry: copy/paste error

### ISSUE THREAD

**Issue by niraj-rana** [GetTerminus/terminus-ui#1133]
Issue: When copying more than one row from excel into CSV Entry component, the first row throws an error saying it is invalid URL. However, if you delete a character and re-type, the issue disappears.
Issue does not occur if you copy one row.

Steps to Recreate:
- Open an excel
- Create two rows with valid name and URL
- Copy both rows
- Paste into the Component

---

NOTE: This is only reproducible when copying more than one cell from Excel. Bug is not present when copying from Numbers or Google Sheets.

**Comment by benjamincharity** [comment]
I have reached out to Marcus for a copy of Excel.
