### ISSUE TITLE
Navigation: Update navigation item's font weight

### ISSUE THREAD

**Issue by dpeet** [GetTerminus/terminus-ui#1139]
Change from `300` to `500`.

Core is currently overriding this. Once updated we should let the core team know the override is no longer needed.

NOTE: This does *not* need to be back-ported to legacy versions.

**Comment by shani-terminus** [comment]
![screen shot 2019-01-23 at 11 36 28 am](https://user-images.githubusercontent.com/44702601/51622590-e3947b80-1f04-11e9-84e3-32f66e59d69e.png)

**Comment by shani-terminus** [comment]
This went out with #1240
