### ISSUE TITLE
Autocomplete single select control.value should be updated when selection is partial or all deleted

### ISSUE THREAD

**Issue by atlwendy** [GetTerminus/terminus-ui#1151]
Core app needs autocomplete form control value updated when selection is deleted by user. This is not a problem with multiple selection, but with single selection, user can use backspace to delete the selection. Form control value doesn't get updated when user does that.

**Comment by benjamincharity** [comment]
We need to address this issue during the next UI/UX/Product sync to discuss the UX issues when using an Autocomplete as a Select.

**Comment by benjamincharity** [comment]
This was handled through the addition of a filterable select.
