### ISSUE TITLE
Input: Gap exists when no label is provided

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1170]
If a ts-input does not have a label, and the input is active, there is a gap where the label should be

![Screen Shot 2018-12-17 at 12.36.34 PM.png](https://images.zenhubusercontent.com/5bdc9e4ea977220c77bd0f30/34a1113e-54c7-47d4-82de-a4ada74dc572)

**Comment by benjamincharity** [comment]
I'm not worried about the gap with no label since a label should always exist. We could add a warning when in devMode and no label is passed in

**Comment by benjamincharity** [comment]
This seems to no longer be an issue
