### ISSUE TITLE
Mat Icon Required Dependencies

### ISSUE THREAD

**Issue by dpeet** [GetTerminus/terminus-ui#1175]
When using Mat-Icon in a table (see code below), I also needed to install @angular/material, which in turn required @angular/cdk.  I also imported them `import {MatIcon, MatIconModule} from '@angular/material';`

Neither were mentioned in the setup instructions or the docs.

```html
<ng-container tsColumnDef="delete" noWrap="true" minWidth="100px">
            <ts-header-cell *tsHeaderCellDef>
              Delete
            </ts-header-cell>
            <ts-cell *tsCellDef="let item">
              <mat-icon
                class="text-danger pointer"
                (click)="deletePage(item.pageUuid)"
              >
                delete
              </mat-icon>
            </ts-cell>
</ng-container>
```

**Comment by benjamincharity** [comment]
Material components are not directly supported. You should use [`<ts-icon>`](https://github.com/GetTerminus/terminus-ui/blob/master/terminus-ui/src/icon/icon.component.md).
