### ISSUE TITLE
DateRange: Port bug fix to 8.x, 10x, & 11x

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1184]
Changes: https://github.com/GetTerminus/terminus-ui/pull/1172/commits/5bb8dfc2303b0e344eb286791b6ff9d7cd29375d

**Comment by benjamincharity** [comment]
@shani-terminus can you update this issue with the current status? Not sure if we're still blocked on this..

**Comment by shani-terminus** [comment]
We'll have to revisit in later versions to see if it creeps up again. It's related to the date formatter, and we were using a beta version.

**Comment by shani-terminus** [comment]
Verified this is working properly in v11. As date formatter is still in beta (and might always be) we'll have to occasionally check this, but no need for the ticket to hang out.
