### ISSUE TITLE
ValidationMessages: Align phrasing for all messages

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1190]
- [ ] Update messages
- [ ] Verify tests are not dependent on specific strings

We have begun aligning all messages to match the format:

- `'${validatorValue.actual}' must be equal to '${validatorValue.compareValue}'`
- `Must contain at least ${validatorValue.uppercase} uppercase letters`,
- etc

We should go through remaining messages to align:

ie: 

```
minLength: `Minimum length ${validatorValue.requiredLength}.`,
```

**Comment by shani-terminus** [comment]
The tests are more lenient, depending on keywords, but not whole phrases. This is not the case for the date and image ratio validators, those tests weren't touched.
