### ISSUE TITLE
Select: Display message when no items were returned by the query

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1201]
The consumer needs a way to tell the user that no options were returned by their query. This message should not appear prior to a query being typed.

- [ ] If a query exists but no options are found, add a single 'blank' option that supports a custom message
  - `autocompleteNoMatchesMessage: string`: Defaults to `No items match your query.`
  - This should not appear if a `showProgress` is true (query in progress)

**Comment by bmalinconico** [comment]
* This message should not appear when the loading status is true

**Comment by benjamincharity** [comment]
This is now offloaded as a consumer responsibility.
