### ISSUE TITLE
CSVEntry: reset() behavior ignores columnCount setting and shows errors

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1238]
csv-entry.component.ts line 634:

``` 
this.columnCount = this.defaultColumnCount;
```

When a CSV table is reset, columns are set to 2, not to what's passed in ts-csv-entry.
Also, if you reset the table, you receive errors for blank cells, which feels weird.

**Comment by benjamincharity** [comment]
NOTE: Although this is a bug in all versions, no one is using the single column feature. So we should push this fix to `latest` but not worry about legacy versions.
