### ISSUE TITLE
Pipe: Truncation

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1249]
Core needs the ability to truncate long text in a usable way.

- [x] Pipe name: `tsTruncateAt`
- [x] The first param takes a positive number and defaults to 0
- [x] It should do nothing if no string is passed in
- [x] When truncation happens, the ellipses character should be inserted
- [x] If no truncation should happen, the ellipses character should not be added
- [x] When added, the ellipses should count as one of the allowed characters
- [x] Truncation should support `start`, `middle`, `end` options (defining where the ellipses appears in the string)
  - [x] This should default to `end`
  - [x] When set to `middle` and an even length is set, the starting string should receive the extra character (ie `'abcdefgh' | tsTruncateAt:6` -> `abc…gh`)

Example usage:

```
{{ 'Here is my string' | tsTruncateAt:7 }} // Outputs: `Here i…`
{{ 'Here is my string' | tsTruncateAt:8:'middle' }} // Outputs: `Here…ing`
```

**Comment by lildziner** [comment]
@shani-terminus Found a use case that will affect us very soon with the Account List Dynamic Segmentation project. We will need to bring in the Global Filters from Hub into the wizard flow and we may need to restrict the display width. Here's an example of how BF handles it - It's annoying to wait for it to ticker tape be to get the whole name. A tooltip approach would be better but we're open to ideas. We would leverage this in menus with long names - all campaigns and tactics and image files have extremely long names.
![globalfilterstruncation](https://user-images.githubusercontent.com/4960080/51766541-d44e3300-20a8-11e9-8e0f-925232d3c39d.gif)
