### ISSUE TITLE
Select: Multiple mode checkboxes are truncating text

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1307]
- This issue is with master.
- I was only able to reproduce in Safari, but others have reported it in Chrome. (I could not replicate in Chrome or Firefox).
- The issue does not seem to be present in the checkbox demo in Safari.

Best guess is it's related to the `display: inline-flex` but haven't found the exact cause.

![Screen Shot 2019-01-30 at 2.56.29 PM.png](https://images.zenhubusercontent.com/59fa074d8a75884b9085aa07/e84420f6-fc5d-4d8c-8341-54b963b693df)

**Comment by atlwendy** [comment]
Some more examples shown on core app...

![image](https://user-images.githubusercontent.com/377552/52059646-61c1d500-2538-11e9-8187-8f920fda24e2.png)
