### ISSUE TITLE
DateRange: Possible bug allows user to manually type into disabled control

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1328]
Engage is seeing an issue where the user is able to type into a field that is disabled. It is visually disabled and the datepicker won't open but manual typing works.

The demo doesn't show that behavior. We should try disabling at the formGroup level, with a flag, and individual control to see if we can replicate.

**Comment by benjamincharity** [comment]
I believe this was fixed 🤞

**Comment by atlwendy** [comment]
Yep. I think so. Should be closed by #1339

**Comment by benjamincharity** [comment]
Closed by #1340
