### ISSUE TITLE
Select: Make filter placeholder/label more explicit

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1352]
Update select filter text to be more explicit:

New text: `Begin typing to filter...`

Originally reported by Niraj.

---

<details>
  <summary>
    Original issue content
  </summary>

Niraj reported a user having confusion over the word "filter..." in this select. 
The solution has yet to be determined. 
- Do we simply want to change this text? If so, what should it be?
- Does this text need to be customizable? If so, what should the default text be?
- Is this a problem for enough users to even warrant a change? If not, close this ticket!
- Something else?

<img width="1139" alt="screen shot 2019-02-12 at 9 28 32 am" src="https://user-images.githubusercontent.com/44702601/52645213-51054d80-2eae-11e9-8ba2-936a7a794f43.png">

Code:
https://github.com/GetTerminus/terminus-ui/blob/master/terminus-ui/select/src/select.component.html#L164

</details>

**Comment by dpeet** [comment]
Some research
[1](https://uxdesign.cc/crafting-a-kickass-filtering-ux-beea1798d64b)
> *Filtering vs Sorting* - In theory, they are different: sorting organises the content according to a certain parameter, filtering removes it from view.
>However, research suggests that for the user, the outcome is roughly equivalent: both surface the most relevant content according to their criteria. During user sessions, Baymard even reports some people to use “sorting” and “filtering” interchangeably.

Google Maps
![image](https://user-images.githubusercontent.com/4729779/52646273-798e4700-2eb0-11e9-9893-530bfe361f95.png)

Adroll
![image](https://user-images.githubusercontent.com/4729779/52646335-9296f800-2eb0-11e9-8bca-1d0a6775c2aa.png)

Salesforce
![image](https://user-images.githubusercontent.com/4729779/52647063-038adf80-2eb2-11e9-9482-8784e6f4eb0b.png)

Gong
![image](https://user-images.githubusercontent.com/4729779/52647100-11406500-2eb2-11e9-853c-1122c5759e28.png)

**Comment by benjamincharity** [comment]
Closing for now as no immediate need seems present.
