### ISSUE TITLE
FileUpload: Error validation feedback is inconsistent

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1357]
When uploading a file with an invalid image ratio, the border color does not turn red, when the error message appears.

Need to explore if this behavior happens for file size. 

Correct behavior is displayed with bad MIME type
![screen shot 2019-02-13 at 10 48 04 am](https://user-images.githubusercontent.com/44702601/52724219-f686f280-2f7c-11e9-967a-d35a2a8e4350.png)

**Comment by atlwendy** [comment]
![image](https://user-images.githubusercontent.com/377552/52725560-78781b00-2f7f-11e9-8e5d-1ba70a953900.png)

Invalid dimension does show red error border.

**Comment by shani-terminus** [comment]
I saw that just now, Wendy. I suppose my machine (or my brain?) was lagging when I noticed the bad behavior earlier.
