### ISSUE TITLE
Select: Allow typing a space in select w/autocomplete

### ISSUE THREAD

**Issue by lildziner** [GetTerminus/terminus-ui#1416]
Use case: User is entering multiple job titles in wizard, user can't use space bar in search.  While putting in all of their job titles, Unity had a really tough time because many of their titles use multiple words eg, for 'Project Manager'. Space is allowed for first typed selection but space is not available when typing subsequent names, eg 'project coordinator' would not be possible to type, only via select with mouse.

![typing-space-fromdemo](https://user-images.githubusercontent.com/4960080/54455645-bb6e0f80-4732-11e9-9ae4-7c52129b9907.gif)
![select-typing-spacebar](https://user-images.githubusercontent.com/4960080/54455646-bb6e0f80-4732-11e9-8bb4-b01325439842.gif)

**Comment by benjamincharity** [comment]
https://github.com/GetTerminus/terminus-ui/blob/master/terminus-ui/select/src/select.component.ts#L1309-L1312
