### ISSUE TITLE
Select: AllowMultiple selects are not independent, they are affecting each other

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1426]
I noticed this while working on 1409, and it needs more investigation as it might just be how the demo is set up.

![Kapture 2019-03-26 at 11.23.44.gif](https://images.zenhubusercontent.com/5bdc9e4ea977220c77bd0f30/e6c5331a-7644-4742-95e0-103665973aa9)

**Comment by atlwendy** [comment]
Probably because they are referencing the same FormControl in demo.

**Comment by benjamincharity** [comment]
Going to ignore this less-than-ideal demo for now since we are beginning work on a completely new demo site.
