### ISSUE TITLE
CSVEntry: Should support values that contain commas

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1427]
Reported by Brian via ProdOps.

Currently a commas are not handled well. We should be encapsulating all input content with `"` to preserve any content containing commas prior to the conversion to CSV format.

- [x] Wrap all input content with double quotes (`"`)
- [x] Escape " already in string

Example:
A company named `The "Cool" Group` becomes `"The \"Cool\" Group"`

Relevant code:
https://github.com/GetTerminus/terminus-ui/blob/master/terminus-ui/csv-entry/src/csv-entry.component.ts#L851

**Comment by bmalinconico** [comment]
Jira Issue: https://terminus.atlassian.net/browse/PI-575?filter=11010
