### ISSUE TITLE
Sass helpers: Change all warnings to errors

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1456]
Our Sass helper functions/mixins should alert the user if used incorrectly. Angular CLI seems to be suppressing `@warn` messages from our helpers so we need to switch them to `@error`.

IMO it's not the best workflow to stop compilation for style errors. But since a warning doesn't make it through to the consumer this is the only way to avoid very difficult to track down bugs.

### Reproduction

1. Pass an incorrect value to a Sass helper (e.g. `z-index: z(foo);`)
1. See no warning in the cli

### Which versions of this library, Angular, TypeScript, & browsers are affected?

- UI Library: all versions
- Angular: v7
- TypeScript: 3.1.6

---

- [ ] Change all instances of `@warn` in our Sass files to `@error`

**Comment by shani-terminus** [comment]
I noticed in my local after a bad input was corrected, I would sometimes get an error: `Cannot read property 'toString' of undefined`. This went away when I stopped the `build:ts:watch` and ran it again.
