### ISSUE TITLE
LogInForm: Deprecate existing submit output and add replacement

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1468]
Custom components should not have event emitters whose names can collide with native methods. Listeners subscribed to an output with such a name will also be invoked when the native event is raised.

- [x] Add a new emitter named `submission` that functions exactly as the existing `submit` emitter does
- [x] Deprecate the `submit` emitter with an `@deprecated` JSDoc comment. Let's not callout specifically which version will remove it as lately we've had to move our changes around.
- [ ] Test the new emitter
- [x] Update JSDoc and usage docs

**Comment by shani-terminus** [comment]
Looks like there isn't a test of the submit, do we need to convert this to INT in order to do that?

**Comment by benjamincharity** [comment]
We don't need to convert to an integration test to cover the submit in this ticket. Ultimately we definitely will convert it, so I'm also not opposed if you did want to do it at the same time.
