### ISSUE TITLE
LogInForm: Revisit form reset hack

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1470]
A code comment tells us we were having trouble resetting form validations so we just destroy the whole form and reinitializing it.

https://github.com/GetTerminus/terminus-ui/blob/release/projects/library/login-form/src/login-form.component.ts#L204-L221

- [ ] We should look into doing this the 'right' way to avoid this hack.
- [ ] Despite the final direction we should expose a method that the consumer can call `resetForm()`
- [ ] Document what is needed and why.

**Comment by atlwendy** [comment]
Taken care by #1287
