### ISSUE TITLE
TabBody: Deprecate outputs with 'on' prefix

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1477]
Prefixing @Outputs with `on` is bad practice: https://angular.io/guide/styleguide#dont-prefix-output-properties

- [x] Duplicate the Outputs with un-prefixed
  - `onCentering` -> `centering`
  - `onCentered` -> `centered`
- [ ] Add new outputs to tests
- [ ] Update usage docs
- [ ] Update JSDocs
- [ ] Add deprecation JSDOC comment to each output

**Comment by shani-terminus** [comment]
These two outputs are only used internally so we can deprecate them without a breaking change. I am closing this ticket and moving forward with the second one.
