### ISSUE TITLE
SCSS: Add tests for all helpers

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1520]
### Is your feature request related to a problem? Please describe.

No, we have a gap in our testing. SCSS testing framework has been defined, use the docs and examples in _color.spec.scss, _a11y.spec.scss, and _spacing.spec.scss to create tests for other functions and mixins.

### Describe the solution you'd like.

Tests for all SCSS 

### Describe alternatives you've considered

An understanding and acceptance of the risks involved with not testing code

**Comment by benjamincharity** [comment]
Closed via #1530
