### ISSUE TITLE
Integration Testing Import Paths

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1559]
After moving to INT tests, imports should be updated to `@terminus/ui/[component-name]/testing`. When creating these files in initial transition to INT, the paths have to be relative, but once they are published/committed, we can update them.

**Comment by benjamincharity** [comment]
@shani-terminus can you figure out which imports need to be addressed and list them in the ticket? Then any outstanding issues that need to be handled first can be added as a dependency below the issue description.

**Comment by benjamincharity** [comment]
closing as this should be part of each individual ticket
