### ISSUE TITLE
RadioGroup: Adjustment to visual checkbox small size

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1569]
This change is needed for LinkedIn Forms.

Currently, the 'small' visual mode simply a smaller responsive ratio. Moving forward, UX would like more control over the display of the visual checkbox.

⚠️  NOTE: This ticket should _only_ affect the *small* visual radio.

- [x] Remove the responsive mixin and hardcode the width to `13.75rem`
- [x] The height should also be hardcoded to a height using `rem`s that allows for:
  - 2 title lines
  - 3 body lines
  - The appropriate top/bottom padding
- [x] Update the component JSDoc comment to include all possible inputs & outputs
- [x] Update usage docs to include instructions about how to use the 'small' visual mode

**Comment by dpeet** [comment]
Related problem (that may need to be it's own issue) is adding the shadow mixin to all of the radio buttons so they are more "button" like

**Comment by benjamincharity** [comment]
@dpeet 	I went ahead and popped that off into it's own issue https://github.com/GetTerminus/terminus-ui/issues/1574
