### ISSUE TITLE
TsSearch: Doesn't submit when users delete content below the minimum character requirement

### ISSUE THREAD

**Issue by deanterm** [GetTerminus/terminus-ui#1700]
Consumers need to be alerted for input changes even when the change is below the minimum character requirement.

- [ ] When the characters are less than the required amount, emit an empty string.
- [ ] Add test(s) to enforce this

```
Visual example (assuming the minimum character count is 2):

Input:     Emission:
------     ---------
a          ''
ab         ''
abc        'abc'
abcd       'abcd'
abc        'abc'
ab         ''
a          ''
```

<details>
  <summary>Original Issue</summary>

#### 1. What is the expected behavior?
If a user types into the search component, and then backspaces until the text has been cleared, or, optionally, highlights all of the text and then deletes it, the search component should emit an event letting the user know the value has changed.

Currently, the only way to make this work is expecting the user to click the `X` to clear the content.

I would expect the `submitted` event would fire anytime a user has stopped typing after a period of time, even if the input was previously filled in, but is now empty.

#### 2. What is the current behavior?
The `submitted` or `cleared` event is not triggered if the input is cleared manually by using backspace or highlight-and-delete of the text.  The only way around this is to assume the user is going to click the `X` to clear the content of the input.

#### 3. What are the steps to reproduce?
1. Type anything into a `ts-search`.  Now delete the text by pressing the backspace key multiple times until your content is cleared.  The `submitted` or `cleared` event is not fired to let the user know the input has changed.

2. Type anything into a `ts-search`. Now highlight the text and hit the backspace or delete key on your keyboard. The `submitted` or `cleared` event is not fired to let the user know the input has changed. 

Providing a reproduction is the *best* way to share your issue.

a) Fork our starter repo: https://github.com/GetTerminus/ui-stackblitz-starter
b) Replicate your issue.
c) Add a link to your replication or attach a zip of your project to this issue.
d) Outline any steps needed to reproduce the issue.

#### 4. Which versions of this library, Angular, TypeScript, & browsers are affected?

- UI Library: 14.9.5
- Angular: 8.2.4
- TypeScript: 3.5.3
- Browser(s): Chrome

#### 5. Is there anything else we should know?
Yes. I have $2 for lunch today and I'm not sure how to spend it. 

</details>

**Comment by benjamincharity** [comment]
> I would expect the submitted event would fire anytime a user has stopped typing after a period of time, even if the input was previously filled in, but is now empty.

@deanterm Definitely understand.  

What's currently causing this is the minimum character count. We only emit once past that count. 

How would you expect it to function with a minimum? Emit an empty string any time the query is below the minimum required characters? Downside is that emitting when below the minimum basically renders our minimum setting useless as the consumer will still need to check the length before submitting a query to the backend.

Maybe we just need to lose that minimum count and let the consumer handle it?

**Comment by deanterm** [comment]
not sure.  the workaround i'm doing is looking at the `changed` event and call `.next` on a `Subject` that has a `debounceTime(500)` in there.  

kinda a tricky, but i bet my $2 lunch money you'll figure out a reasonable solution.
