### ISSUE TITLE
Menu: Add another option for the utility menu icon

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1715]
Currently we support a `standard` trigger and a `utility` trigger. We need to add another trigger type to support a product need for a settings menu.

- [ ] Add `settings` as a type to `TsMenuTriggerTypes`
- [ ] Add another getter `isSettingsMenu`
- [ ] Change template ngIf to `isUtilityMenu || isSettingsMenu`
- [ ] Use ternary to output the correct icon in the template
- [ ] Add both icon menu types to the usage docs
- [ ] Add tests

**Comment by dpeet** [comment]
Below is a comp where it is used, but let's put this on hold for now as I dig back into this project

<img width="197" alt="67310266-6d409c00-f4cb-11e9-8630-308613bf4f81" src="https://user-images.githubusercontent.com/270193/67310441-bdb7f980-f4cb-11e9-9301-bc7cd92ba9bc.png">

**Comment by benjamincharity** [comment]
Not handling for now
