### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#18]
- Types
  - success
  - info
  - error
- Should support time based dismiss
- Should support action based dismiss
- 🤔 placement: Pinned to generating container.
  - Caveat: If this cannot be guaranteed, they should be floating in the top right (ie growl)

**Comment by bmalinconico** [comment]
This also can include the Reducer / Actions logic: https://github.com/GetTerminus/terminus/tree/angular_ui/gui/src/app/features/flash-messages

**Comment by benjamincharity** [comment]
Moved: https://www.pivotaltracker.com/story/show/147835399
