### ISSUE TITLE
Selectionlist: when chip presented it grows the selection box higher

### ISSUE THREAD

**Issue by atlwendy** [GetTerminus/terminus-ui#1944]
Before releae `15.10.1`, selection box with chip is taller than without chip...

![image](https://user-images.githubusercontent.com/377552/72632072-7a7ef280-3923-11ea-9168-24221fa1e9fe.png)

After that release, selection box with chip is shorter than without chip..

![image](https://user-images.githubusercontent.com/377552/72636307-c6826500-392c-11ea-855b-105bfd19ac0e.png)

We need to make sure the selection box stays the same with or without using chip.

**Comment by benjamincharity** [comment]
Handled in https://github.com/GetTerminus/terminus-ui/pull/1954
