### ISSUE TITLE
Move UI library repo into nested Angular CLI projects

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#2041]
This move is needed so that we can manage both the demos and the regression testing source within our library project.

--- 

Structure should be:

```
dist/
node_modules/
projects/
  demo/
    src/
  visual-regression/
    src/
  library/ 
    autocomplete/
    etc...
```

- [ ] Set up whole new cli project (NOTE: make sure we are using angular 8 not 9)
- [ ] Move ui library files over
- [ ] Move demo project over
- [ ] Add regression project
- [ ] Verify library build works
  - [ ] Verify all paths in gulp and ngpackagr files
- [ ] Verify demo build works
- [ ] Verify regression build works
- [ ] Verify Jest is used for all tests (jasmine/karma is not present)
- [ ] Verify TS paths work

---

**NOTE**

When you create the new cli repo originally, I’d use the flags to **a)** don’t create git repo **b)** don’t make initial commit, **c)** don’t create initial project.

This is better for us since we don’t want a ‘default project’ outside the projects folder. Then you just generate both projects via the ng g application MyProject command so they are all equally nested

See https://angular.io/cli/generate for all flags etc

Then, this is the easiest way to switch to Jest that I’ve found: https://medium.com/angular-in-depth/angular-cli-ng-test-with-jest-in-3-minutes-v2-1060ddd7908d

**Comment by benjamincharity** [comment]
@atlwendy have you already picked this one up?

**Comment by atlwendy** [comment]
@benjamincharity yes I've started on it... forgot to move the card, as always..
