### ISSUE TITLE
Drawer: Should have a class representing the current state

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#2171]
It would be much easier for consumers to style dynamically if there were classes on the drawer to indicate state.

- [ ] Add a class to indicate state
    - When collapsed `ts-drawer.ts-drawer--collapsed`
    - When expanded `ts-drawer.ts-drawer--expanded`

**Comment by atlwendy** [comment]
Those classes exist in drawer container already. No need to duplicate them..
