### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#254]
- What do we name this component? Flash/Toast/Growl/Alert/etc
- Will be created using the Portal ability of the CDK
- Should support multiple concurrent messages
- Should support the types: `success|info|error`
- Should support time based dismiss
  - User interaction should pause timer
- Should support action based dismiss
- Should be pinned to the bottom of the generating container.
- Should support rich content (primary links)

Resources:
- Existing implementation: https://github.com/GetTerminus/terminus/tree/angular_ui/gui/src/app/features/flash-messages
- https://material.angular.io/components/snack-bar/overview
- https://material.io/guidelines/components/snackbars-toasts.html

**Comment by sunbuns** [comment]
@benjamincharity @bmalinconico - We have been discussing a need for toast notifications especially with the new Campaign Overview CSV file generation state and file ready to download state. There isn't a good way in the UI to alert the user the file is being generated and when the file is ready for download.

**Comment by shani-terminus** [comment]
It would be worthwhile for the core team, when implementing any type of time-based help/hint alert, to track that need. We can take those analytics to improve the UX and reduce the need of such help/hint alerts.

**Comment by benjamincharity** [comment]
On hold while Engage runs a notifications experiment.
