### ISSUE TITLE
Atom: Tabs

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#284]
A component to show tabular content.

- Tab Collection
  - [x] Tabs should be able to be added/removed dynamically
    - [x] Should be able to inject at any index
  - [x] Tab switching should be animated
  - [x] Should be able to align tabs or stretch to fill available space `[tabAlignment]="left|center|right|stretch"`
    - [x] Tab width is dynamic to the tab label content in modes: left, center, right
    - [x] All tabs are the same width when set to stretch
  - [x] Should allow programmatic control through input `[selectedIndex]` (this also allows for default selection)
  - [x] Should accept theme
  - [x] Should support keyboard controls
    - [x] `LEFT_ARROW` focus previous tab
    - [x] `RIGHT_ARROW` focus next tab
    - [x] `HOME` focus first tab
    - [x] `END` focus last tab
    - [x] `SPACE|ENTER` switch to focused tab
  - [x] Should have arial label `role="tablist"`
  - [x] Events
    - [x] `focusChange(TsTabChangeEvent)`
    - [x] `selectedIndexChange(number)`
    - [x] `animationFinished(void)`
    - [x] `selectedTabChange(TsTabChangeEvent)`
  - [x] Should support 'inverted' state where tabs are at the bottom
- Tab Trigger
  - [x] Should be able to disable a tab `[isDisabled]`
    - [x] Should have `tabindex="-1"`
    - [x] Should have `not-allowed` cursor
  - [x] Should have appropriate aria labels
    - `role="tab"`
    - `aria-selected="true"`
  - [x] Should have a cursor: pointer
  - [x] Should have ripple effect when clicked
  - [x] Label should support simple text via `@Input` or custom template via directive
  - [x] Active tab should have focused style (underline/bar, darker color)
  - [x] Should support hover state (active tab styles without moving the underline)
- Tab Body
  - [x] Hidden content is not added to the DOM (see expansion panel template directive)
  - [x] Should have appropriate aria labels
    - `role="tabpanel"`
    - `aria-labelledby="tab-id"`
  - [x] If tab content has varying height, it should animate between heights
  - [x] Overflowing text should be truncated with an ellipses

#### Example change event class:

```typescript
class TsTabChangeEvent {
  index: number;
  tab: TsTabComponent;
}
```

#### Example usage:

```
<ts-tab-collection>
  <ts-tab>
    <ts-tab-label>
      Tab 1
    </ts-tab-label>

    Content 1
  </ts-tab>

  <ts-tab>
    <ts-tab-label>
      Tab 2
    </ts-tab-label>

    Content 2
  </ts-tab>
<ts-tab-collection>
```

**Comment by baigfaizan95** [comment]
@benjamincharity i am working on this tabs module will give a PR soon
