### ISSUE TITLE
Atom: Chip

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#285]
### Purpose

We've recently been solving for some complex user interaction cases around allowing a user to create large lists (ie 50+) from even larger lists (ie 50,000+). When approaching that problem with a toolset based around form controls we have struggled to create a good experience. I don't find that surprising since there are no standard web inputs that exist to solve this need.

In the mentioned user need, the user is not really selecting (select) or free-writing options (autocomplete) - they are really _searching_ and adding to a collection.

The hope is that if we can allow a collection to be shown separately from the actual form of user input, this would open up a wider array of creative solutions around how the user makes selections when creating these large lists.

In turn, this will also allow us to fix a few issues in our existing autocomplete where it is not functioning as a true autocomplete as users expect.

---

### Chip

- [ ] Should support removal icon/action
  - [ ] `[isRemovable]="true"`
  - [ ] When removable a clickable `x` icon should be present at the right of the chip
  - [ ] Should expose method to allow programmatic removal `remove()`
  - [ ] Should not allow removal when the parent collection is in readonly mode.
- [ ] Should support selection
  - [ ] This can be disabled `[isSelectable]="false"`
  - [ ] Selection ability should take into account the internal property `chipCollectionIsSelectable` which is set by the chip collection when the collection is marked as selectable.
  - [ ] Should reflect selected state via styles
- [ ] Should support focus
  - [ ] Should support programmatic focus via input `[isFocused]="true"` and public method `focus()`
  - [ ] Should reflect focused state via styles
- [ ] Should support selection
  - [ ] Should support programmatic selection via input `[isSelected]="true"` and public method `select()`
  - [ ] Should support multiple selection `[allowMultiple]="true"`
- [ ] Can be disabled `[isDisabled]="true"`
  - [ ] All interaction is disabled
  - [ ] If parent collection is disabled, the chip should be disabled too
  - [ ] Should be styled to appear disabled
- [ ] Events
  - [ ] `selectionChange: TsChipSelectionChange`
  - [ ] `destroyed: TsChipEvent`
  - [ ] `removed: TsChipEvent`
- [ ] Should have accessibility support:
  - [ ] `aria-role="option"`
  - [ ] `aria-disabled="true"` true when `isDisabled` is true
  - [ ] `aria-selected="true"` true when `isSelected` is true
- [ ] When chip is removed, the new chip that takes it's place should gain selection
  - [ ] If there is no chip at the vacated index, the previous chip should gain selection
- [ ] Should display ripple effect when clicked
- [ ] Should support keyboard controls
  - [ ] `DELETE|BACKSPACE` remove chip
  - [ ] `SPACE|ENTER` select chip
  - [ ] `SHIFT+SPACE` add/remove chip from selection group (when `allowMultiple`)
  - [ ] `TAB` if focus is chip, using `TAB` should focus on input field when used in autocomplete component
- [ ] Inputs
  - [ ] `isDisabled`
  - [ ] `isFocused`
  - [ ] `isRemovable`
  - [ ] `isSelectable`
  - [ ] `isSelected`

### Chip collection

> NOTE: This is not a standard chips input so there is no `FormControl` or `ngModel` support. This is simply a display for a collection of items that emits events allowing the consumer to adjust the collection accordingly.

- [ ] Should have accessibility support:
  - [ ] `aria-role="listbox"` Only set when the collection contains at least one item.
  - [ ] `aria-required="false"` Always false since we are not creating a true form control
  - [ ] `aria-disabled="false"` true when `isDisabled` is true
  - [ ] `aria-orientation="horizontal|vertical"` reflects the `orientation` property
  - [ ] `aria-multiselectable="true"` true when `allowMultiple` is true
  - [ ] `aria-activedescendant="chip-id"` takes the ID of the chip most recently interacted with regardless of chip's selected state
  - [ ] `aria-readonly="true"` true when `isReadonly` is true
- [ ] Should support disabled state via input `[isDisabled]="true"`
- [ ] When collection is focused:
  - If no chips are selected, the first chip should be focused
  - If one or more chips are selected, the first selected chip should be focused
- [ ] Should support keyboard controls
  - [ ] `ARROW_UP|ARROW_LEFT` focus the next active chip
  - [ ] `ARROW_DOWN|ARROW_RIGHT` focus the previous active chip
  - [ ] `HOME` focus the first enabled chip
  - [ ] `END` focus the last enabled chip
  - [ ] `CTRL+A` select all chips
    - [ ] If all chips are selected, this should unselect all chips
  - [ ] `CTRL+SHIFT+HOME` selects focused chip and all enabled chips up to and including the first chip
  - [ ] `CTRL+SHIFT+END` selects focused chip and all enabled chips up to and including the last chip
- [ ] Should support mouse controls
  - [ ] `SHIFT+CLICK` on a chip should add/remove it from the selection group
    - [ ] This only works when `allowMultiple` is true
- [ ] Collection can define if any chips are selectable
  - [ ] `[chipsAreSelectable]="true"`
  - [ ] When set, it sets property on each contained chip `chipCollectionIsSelectable`
- [ ] Events
  - [ ] `collectionChange: TsChipCollectionChange `
- [ ] Should allow orientation change between vertical and horizontal `[orientation]="horizontal"`
  - [ ] When vertical, each item is displayed on its own line.
- [ ] Should support readonly mode `[isReadonly]="true"`
  - [ ] When true, the user can navigate, focus and select chips, but the collection should not emit `remove` events
- [ ] Should expose public methods to select or deselect all chips `selectAll()` `unselectAll()`
- [ ] Collection should wrap when too many options exist to be displayed on a single line.
- [ ] Inputs
  - [ ] `allowMultiple`
  - [ ] `isDisabled`
  - [ ] `isSelectable`
  - [ ] `isReadonly`
  - [ ] `orientation`

### General

- [ ] Update component count for the primary README badge
- [ ] Update primary readme table for status of chips and appropriate links

### Event classes

```typescript
class TsChipEvent {
  chip: TsChipComponent;
}

class TsChipSelectionChange {
  chip: TsChipComponent;
  selected: boolean;
}

class TsChipCollectionChange {
  collection: TsChipCollectionComponent;
  collectionValue: any;
}
```

### Example usage:

```html
<!-- Single chip -->
<ts-chip>
  foo
<ts-chip>
```

```html
<!-- Chip collection -->
<ts-chip-collection>
  <ts-chip *ngFor="let chip of myChips">
    {{ chip.value }}
  </ts-chip>
</ts-chip-collection>
```

### Implementation details

- Chip should leverage `FocusableOption`
- Collection should leverage `FocusKeyManager` and `SelectionModel`

### Resources:

- https://material.angular.io/cdk/a11y/overview
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role
- https://material.io/guidelines/components/chips.html
- https://material.angular.io/components/chips/overview
- https://github.com/angular/components/blob/master/src/material/chips/chip.ts

**Comment by dpeet** [comment]
Feedback, `Should support selection` is mentioned twice

**Comment by benjamincharity** [comment]
More feedback from @dpeet:

> 1) I noticed you said an X is on the left whereas material has it on the right

Whoops. 

_holds both hands up in the shape of an L..._ 

Fixed 👍 

> 2) will the chip collection be able to wrap in horizontal mode? or scroll if not wrapping?

Current plan is for wrapping to occur. I've added this to the requirements list.

> 3) what do you think about the ability to “hover” over a chip to see the full text (for urls for example)

Definitely needed functionality IMO. Since the consumer is in charge of outputting the chips they can truncate the displayed chip value with our swanky new TsTruncatePipe, then wrap the chip with the tooltip component to show the full string on hover. This saves us from needing to get fancy internally and determine if a value should be truncated etc.

> 4) do we want to build in the ability to have optional thumbnails on the left?

Do you mean adding an image inside of the chip? Currently there are no plans to support media inside chips. It seems that an image would be hard to see at a standard chip size. Possibly we can create a 'jumbo chip' version at some point if this is needed?

> 5) do we want to support “editable” chips (click on it and it transforms back to text to be edited)

Not in this incarnation. This is a very 'dumb' chips display. It's not attached to any type of FormControl or internal model - it just displays a list of items that is passed to it and emits events when the user interacts. So any editing would need to happen outside of this.

Part of the reason this is being created is to allow the separation of creation or editing from displaying. There will still be a place for something like an autocomplete with chips, but this component will allow us to display a list of items not directly attached to a specific form of user input. The goal is to allow us to choose the best interaction method for the specific use-case.

> 6) for errors, do we want the chip to display the error, or not allow the chip to be created if there’s an error

Since this is a 'dumb' display there is no possibility for this component to get into an error state. That would need to bubble up wherever the creation or editing is happening.

**Comment by dpeet** [comment]
for 4)
Both thumbnails and icons (examples below)
![image](https://user-images.githubusercontent.com/4729779/54700686-df9e6780-4b09-11e9-8323-5011d0195ecd.png)
![image](https://user-images.githubusercontent.com/4729779/54700711-e9c06600-4b09-11e9-8bc2-d3c7b76e3ff0.png)
I could see icons potentially being useful, moreso than thumbnails, but open to both

6) So would we just not allow the entry then? Example - user starts typing in an autocomplete, and hits enter with text that doesn't match something in the database
here is a visual from MD just for reference
![image](https://user-images.githubusercontent.com/4729779/54700933-4d4a9380-4b0a-11e9-9493-06fd8edcfef6.png)

**Comment by benjamincharity** [comment]
### 4.A

I have seen that Material supports images, I just am not sure what our use-case would be? I haven't seen anything existing or proposed that could make use of adding/removing users via chips. And when thinking about what images we do have, I'm not sure that displaying a creative in a space that small would be useful.

### 4.b

I could see icons possibly being useful. That is something that would be pretty easy to add in after the fact if/when we hit a true need for it. 

There is balance I am trying to find between building ahead to be prepared and not building in too many features we don't have a current (or planned) use for. I definitely have not perfected this..but that is the lens I am using during these discussions. Feel free to push back as I may just not know of areas where certain features may be useful.


### 6

Correct. In the attached Material example I would propose that an autocomplete may not be the optimal solution for the implied need. I'd prefer to help the user avoid the error state completely by not allowing them to select something that isn't valid.

And for this component specifically, it is really a display component - not a user input component. This is designed to be used with (or without) another form of user input. We currently do not have any plans to remove our Autocomplete w/chips so that will still exist. But the genesis of this component was really the need to display a collection of selections separate from the user input control. The hope is that this allows us to rethink some more complex cases where a native control such as an autocomplete input doesn't really offer a great experience (eg a user creating a list of 50 items).

---

My bad on the confusion around this - I jumped straight into requirements without really defining the purpose of the new component. I've added a 'purpose' section to the issue above and will try to begin elevating the _true_ goal at the top of our issues going forward.

**Comment by dpeet** [comment]
### 4A
agreed, sounds good!

### 4b
Leyda and I couldn't come up with anything offhand, so we can table it and improve the component if we have that need.  I'll keep my eyes open as we spin up q2 projects
