### ISSUE TITLE
Expansion Panel / Accordion

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#289]
This component will have two primary use-cases:

a) A stand-alone expansion panel
b) Multiple panels used as an accordion

### Features

- [x] Should allow multiple sections to be opened at the same time
  - [x] Should have a setting to determine if only a single section may be opened
- [x] Should open/close smoothly (animated)
  - Static height should **not** be needed for animation
  - [x] Both the trigger and body height should animate
- [x] Should expose top level expanded/closed classes to allow trigger customization by consumer
- ~Should use transparency to fade the bottom (showing more items exist)~
  - This would require content to be rendered at all times which conflicts with the requirement for deferred loading of panel content.
- [x] Should be able to set a section as open by default with the `expanded` input
- [x] Should be able to disable sections
  - [x] Should still be able to programmatically control disabled triggers & panels
  - [x] Disabled triggers should have the appropriate cursor
- [x] Should defer rendering content until opened when using `ng-template`
  - `tsExpansionPanelContent`
- [x] Multiple expansion panel components can be used together as an accordion
  - `ts-accordion`
- [x] Each trigger should support simple text content
  - [x] Should also support a title and description component within the trigger
  - `<ts-expansion-panel-trigger>`
    - `<ts-expansion-panel-title>`
    - `<ts-expansion-panel-description>`
  - [x] Triggers should have customizable collapsed and expanded heights
    - `collapsedHeight: number`
    - `expandedHeight: number`
  - [x] Trigger should have visible focus state
- [x] Should support an 'action row' at the bottom (this allows for a 'stepper' functionality)
  - `ts-expansion-panel-action-row`
  - [x] Action items are right aligned using flexbox
- [x] Should be able to hide toggle icon (to support 'stepper' functionality)
- [x] Panel events:
  - [x] `opened()`
  - [x] `afterExpand()`
  - [x] `closed()`
  - [x] `afterCollapse()`
  - [x] `destroyed()`
  - [x] `expandedChange(boolean)`
- [x] Accordion events:
  - [x] `destroyed()`
- Accessibility
  - [x] Triggers should have the `role="button"`
  - [x] Triggers should represent expanded state via `aria-expanded="false"`
  - [x] Triggers should have `aria-controls="content-1"` set with the value matching the associated panel's ID
  - [x] Panel visible state should be represented by `aria-hidden="true"` and toggle the value appropriately
  - [x] Panel should have `attr.aria-labelledby` with the ID of the matching trigger
  - [x] Panels should have `role="region"`
- [x] Should support keyboard controls
  - Accordion:
    - [x] `HOME` should focus first trigger
    - [x] `END` should focus last trigger
    - [x] `ENTER|SPACE` should toggle the focused trigger
- [x] Accordion should expose group controls:
  - [x] `openAll()`
  - [x] `closeAll()`
- [x] Panel should expose individual controls:
  - [x] `open()`
  - [x] `close()`
  - [x] `toggle()`

---

### Usage examples

```html
<!-- Stand-alone panel -->
<ts-expansion-panel>
  <ts-expansion-panel-trigger>
    Here is my trigger!
  </ts-expansion-panel-trigger>

  And here is my standard panel content.
</ts-expansion-panel>
```

```html
<!-- Accordion Mode -->
<ts-accordion>
  <ts-expansion-panel>
    <ts-expansion-panel-trigger>
      Here is my trigger!
    </ts-expansion-panel-trigger>

    And here is my standard panel content.
  </ts-expansion-panel>

  <ts-expansion-panel>
    <ts-expansion-panel-trigger>
      Here is second trigger!
    </ts-expansion-panel-trigger>

    And here is another content section.
  </ts-expansion-panel>
</ts-accordion>
```

```html
<!-- Title & Description -->
<ts-expansion-panel>
  <ts-expansion-panel-trigger>
    <ts-expansion-panel-title>
      Panel title
    </ts-expansion-panel-title>

    <ts-expansion-panel-description>
      A brief description of the panel
    </ts-expansion-panel-description>
  </ts-expansion-panel-trigger>

  And here is my standard panel content.
</ts-expansion-panel>
```

```html
<!-- Action Panel -->
<ts-expansion-panel>
  <ts-expansion-panel-trigger>
    My title
  </ts-expansion-panel-trigger>

  And here is my standard panel content.

  <ts-expansion-panel-action-row>
    <button>Previous</button>
    <button>Next</button>
  </ts-expansion-panel-action-row>
</ts-expansion-panel>
```

```html
<!-- Lazy-loaded panel contents -->
<ts-expansion-panel>
  <ts-expansion-panel-trigger>
    My title
  </ts-expansion-panel-trigger>

  <ng-template tsExpansionPanelContent>
    My deferred content
  </ng-template>
</ts-expansion-panel>
```

---

Resources:
- https://material.io/guidelines/components/expansion-panels.html
- https://github.com/angular/material2/releases/tag/2.0.0-beta.7 (no docs yet)
- https://medium.com/@simonb90/hidden-features-of-angular-material-cdk-ee07066d73d1
- https://github.com/angular/material2/tree/master/src/lib/expansion

**Comment by dpeet** [comment]
Example of a desirable feature - alpha transparency mask on the data to indicate there is content below the expansion line

![image](https://user-images.githubusercontent.com/4729779/51932835-fcea6b80-23cd-11e9-8a2c-c5db034ffd0e.png)

**Comment by benjamincharity** [comment]
cc @deanterm for review
