### ISSUE TITLE
Drag and drop to upload a component

### ISSUE THREAD

**Issue by Shelton** [GetTerminus/terminus-ui#431]
As a user, I want to drag a CSV file into the upload box within the tactic creation wizard in order to upload my list of accounts/companies.

- Specified area (full screen vs specific placement)
- Copy instructions contextual to drag area
- Visual progression for large file uploads
- Post upload messaging with relevant file read data

**Comment by Shelton** [comment]
#288

**Comment by benjamincharity** [comment]
Merged into #288
