### ISSUE TITLE
Validator: numbers

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#451]
Create a validator to enforce a specific amount of numbers.

1. Use the regex creator from ngx-tools: https://github.com/GetTerminus/ngx-tools/blob/master/ngx-tools/regex/README.md#containsnumbersregex
2. Consumer passes in the minimum amount required: `validationService.containsNumbers(2)`
3. We pass that number to `createContainsNumbersRegex(2)` to create our regex.
4. Use regex to validate.
5. Add validation message to `validation-message.service`
6. Add example to demo

**Comment by bmalinconico** [comment]
Suggestion, validate the format and inherit from there. numeric only would be /\A[0-9]*\z/ etc

**Comment by benjamincharity** [comment]
We can already enforce the format in the input by adding `type="number"` but I'm assuming we still want validation at the form level?
