### ISSUE TITLE
Component definition: Simple Card

### ISSUE THREAD

**Issue by Shelton** [GetTerminus/terminus-ui#505]
Definition:

Design specs:
Zeplin: [Simple Card](https://app.zeplin.io/project/5a54c61b8eae3881dd83bfa9/screen/5a54c67013e46f390965b110?)

Usage criteria:
1.

**Comment by Shelton** [comment]
Top section elements:

1. Title
2. Subtitle
3. Close / Menu button
4. Title Icon

Main section:

1. Action item(s)
2. Copy (paragraph)
3. Image

Footer section:

1. Action item(s) - cancel button / progress button

**List of potential cards to be built off of the Simple Card design.**

- [ ] Card with center title (none)
- [ ] Card with center title + close/menu (login as)
- [ ] Card with title + subtitle + paragraph copy
- [ ] Card with close/menu
- [ ] Card with title + subtitle + main action + secondary action
- [ ] Card with title + subtitle + main action element

**Comment by benjamincharity** [comment]
@Shelton can you invite me to Zeplin?
