### ISSUE TITLE
Default selection for radio group doesn't work.

### ISSUE THREAD

**Issue by kal93** [GetTerminus/terminus-ui#678]
Not sure whether its allowed to raise issues on this repo but I came across one.

The default selection for radio group on initial load is not reflected.

1.Issue can be found in terminus stackblitz.
https://stackblitz.com/edit/terminus-ui-demos?file=app%2Fcomponents%2Fradio%2Fradio.component.ts

2.Check the `radio.component.ts` line 25 & line 42  in `DEMO_ITEMS` & `DEMO_ITEMS2` respectively.

**Expected behaviour:**
Baz2 radio-button should be selected by default.

**Comment by benjamincharity** [comment]
Allowed and much appreciated!

Definitely a bug! Thanks for raising the issue!

**Comment by benjamincharity** [comment]
Fixed in https://github.com/GetTerminus/terminus-ui/releases/tag/v6.0.3

Demo update: https://github.com/GetTerminus/terminus-ui/releases/tag/v6.0.3

Thanks again @kal93!
