### ISSUE TITLE
Table: Should support columns with various alignment

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#767]
The column should support an input `alignment`. This takes one of 3 values: `left|center|right`. When used, each cell should get a class that adds the correct CSS (eg `text-align: center`).

```typescript
export type TsTableColumnAlignment
  = 'left'
  | 'center'
  | 'right'
;
```

- [ ] Add input `alignment: TsTableColumnAlignment` to `TsCellDirective`
- [ ] When the input is set, a class should be added to the cell that appropriately aligns the text
- [ ] Add tests
- [ ] Add documentation
- [ ] Add to one (or two) of the demo columns

**Comment by edwin-terminus** [comment]
text-align: left|right|center|justify|initial|inherit;

text-align also supports justify, initial and inherit.  do we want to filter these out and ignore them?  should we just make sure the @Input alignment is not 'undefined' and set text-align to the value of @Input alignment?

**Comment by benjamincharity** [comment]
👍 My vote is to filter them out. (at least until UX says they have a need for `justified`, etc)

What we've done in a few places is do a check and log an error when in dev mode: 

https://github.com/GetTerminus/terminus-ui/blob/ef1ec246451b313a1c225753bfc41ebe7f844e8a/terminus-ui/src/button/button.component.ts#L236

We'd probably want to fallback to the default value in that case too.

**Comment by edwin-terminus** [comment]
that makes sense

**Comment by bbarry** [comment]
Does this work correctly?

https://github.com/GetTerminus/terminus-ui/blob/release/projects/library/table/src/cell.ts#L55

The function seems to always add the class `ts-cell--align-right` ( even if you explicitly specify alignment to be 'left' or 'center')

**Comment by benjamincharity** [comment]
Thanks for calling this out; you are absolutely right!

Latest release has a fix for this with improved test coverage 👍 (https://github.com/GetTerminus/terminus-ui/blob/release/CHANGELOG.md#1703-2020-03-06)
