### ISSUE TITLE
Add Image Radio Buttons to Design System

### ISSUE THREAD

**Issue by dpeet** [GetTerminus/terminus-ui#827]
**Overview of the Issue** - In several places in the platform Terminus radio buttons with an image as the selector.  Terminus needs a defined component for that.

**Motivation for or Use Case** - When using an image/text as a radio selector instead of the more traditional radio buttons

**Suggest a Fix** - Several solutions were prototyped and the best solution is from the lightning design system "Visual Picker" component, Non Coverable Content variant.  See live version [here](https://www.lightningdesignsystem.com/components/visual-picker/) and [here](https://www.lightningdesignsystem.com/guidelines/animation/gallery/)

**Specific Elements**
- [x] Default Case
- [x] onHover blue outline
- [x] cursor change onMouseover
- [x] checkmark on selection

**Comment by benjamincharity** [comment]
@dpeet questions:

1. Linked demo above has content outside of the radio box that is included in the radio (clicking that content selects the box above it). Do we have a use-case for this? Or will our content live only inside the radio box?

1. I'm assuming we'll need to enforce an aspect ratio for the boxes. Is this a single allowed aspect ratio? Or do we need a few options like `TsCard`? (see [`TsCard` aspect ratios](https://github.com/GetTerminus/terminus-ui/blob/master/terminus-ui/src/card/card.component.md#aspect-ratio)) Salesforce seems to hard-code width/height which doesn't scale well responsively.

**Comment by dpeet** [comment]
1. I would only worry about in the radio box for now.  Simpler, and a more expected behavior
2. My gut says lets pick an enforced aspect ratio (probably at the radio group level) and use that.  We can come back and provide the option if we need to, but I would favor consistency first.
