### ISSUE TITLE
Confirmation: Allow positioning

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#830]
- [ ] Allow position to be set
  - before, after
  - above, below (will be centered)
- [ ] Create scss classes to position arrow of the modal based on allowed positions

<details>
  <summary>Original issue</summary>

  - if the confirmation appears close to the viewport edge, ~padding disappears~ (cannot repro) and the modal spills outside of the viewport.
  - ~the confirmation directive is setting `display: block` on the `ts-button`~
  - confirmation may not be centered if `ts-confirmation` is filling width of parent:
<img width="559" alt="screen shot 2018-05-14 at 7 14 22 am" src="https://user-images.githubusercontent.com/270193/39994204-8f24619a-5746-11e8-9e64-8d811b4be03d.png">
  ~ - Button should not be able to scroll away from popup~
moved to https://github.com/GetTerminus/terminus-ui/issues/1391

~Blocked until Material is upgraded to 6.x: https://material.angular.io/cdk/overlay/overview~

</details>

**Comment by shani-terminus** [comment]
Modal is set to be centered, but it appears relative to the container, not the button. This is set in confirmation.directive.ts `createOverlay()` function

The little triangle is set in CSS (`:before`)

**Comment by benjamincharity** [comment]
@shani-terminus now that #1391 has been split out, is this ticket finished? Or are there outstanding items to check?

**Comment by shani-terminus** [comment]
I have confirmed the modal will be outside of the viewport if the button is too close to the bottom, and noted the modal is centered even if the button is justified. I think this ticket is still relevant but we need to figure out what we want as the solution:
- allow core to set a position? (we'd need both left/right and top/bottom)
- calculate the position of the button relative to the edge of the viewport and adjust automatically?
- something else?

**Comment by benjamincharity** [comment]
> allow core to set a position? (we'd need both left/right and top/bottom)

**Comment by benjamincharity** [comment]
> allow core to set a position? (we'd need both left/right and top/bottom)

This is my vote. Much simpler than dynamic positioning

**Comment by shani-terminus** [comment]
Tooltip position is a good start, but this one is more elaborate as it has to accommodate two positions, and we'll need need new scss rules for the different variations.
