### ISSUE TITLE
DataViz Decisions

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#846]
Goal: Minimize fast-follow re-work while not building in support for items we don't currently need.

---

For these decisions I expect there to be 2-3 layers of settings:

1. Layer 1: base options for 90% of use-cases (legends, colors, etc)
2. Layer 2: tweaks for individual chart types (eg disable crosshairs for maps)
3. Layer 3: tweaks for specific data. (I would love to not need this level of settings, but is it possible for specific datasets we may need to change how many decimal places are supported etc?)

---

## General data-viz guidelines

In past big-data dashboard projects, these were some foundational rules I followed based on books, posts, etc.

- Only use color variations to show data.
- Order data appropriately (by alpha/date/value)
- It should be able to be understood when printed in b/w.
- Start the y-axis at 0.
- Always right-to-left unless the direction change somehow makes the data more clear.

#### Specific chart guidelines

- Line
  - Usage: (x/y) continuous/trend data / comparing 2 sets
  - Only solid lines unless showing gaps in data etc
  - No more than 4 lines if possible.
  - Scale so all data points fit in the bottom 2/3rds of the y-axis total height
- Area
  - Usage: (x/y) overall and individual trend information
  - Use semi-transparent fills
- Bar
  - Usage: (x/y) trend data / multiple data sets
  - Use horizontal labels (possibly angled if _really_ needed)
  - Space between bars should be 1/2 the width of the bar
  - Stacked bar
    - Usage: show composition of each item being compared
  - Horizontal bar
    - Usage: use if labels are long
- Pie/doughnut
  - Usage: (x/y/z of 100%) how categories represent part of a whole
  - Only when less then 6 categories
  - All categories should always equal 100%
  - Place largest section at 12pm and continue clockwise
  - Should try to avoid since people cannot judge slice areas correctly (doughnut does lessen this issue)
- Gauge (linear, angular, thermometer)
  - Usage: (x in range y-z) show range on scale (optionally show ranges within scale)
- Bullet
  - Usage: like gauge: (a in range b-c with goal line of d): reveals progress toward a goal
- Scatter
  - Usage: (x/y) looking for outliers or for understanding the distribution of your data
  - Best used to show correlation in large data set
  - Can add trend lines (max 2)
- Bubble
  - Usage: (x/y/volume) similar to scatter but with third data set (or rather, another grouping)
  - Scale bubbles by area, not diameter
  - Always use circles, not custom shapes
- Heat map
  - Usage: show variation with shade or variation between two colors
  - Use 3-5 ranges with +/- for extremes (eg `10-20/20-30/40+`)

---

- [Basic chart demos](https://www.highcharts.com/demo)
- [Stock chart demos](https://www.highcharts.com/stock/demo)
- [Map demos](https://www.highcharts.com/maps/demo)

---

### What charts do we support?

Currently I'm planning on (links are to highchart demos):

- BasicCharts:
  - [bar](https://www.highcharts.com/demo/bar-basic)
    - [stacked bar](https://www.highcharts.com/demo/bar-stacked)
    - bar percentage
  - [line](https://www.highcharts.com/demo/line-basic)
  - [column](https://www.highcharts.com/demo/column-basic)
    - [stacked column](https://www.highcharts.com/demo/column-stacked)
    - [stacked percentage](https://www.highcharts.com/demo/column-stacked-percent)
  - [pie](https://www.highcharts.com/demo/pie-basic)
    - [pie with drilldown](https://www.highcharts.com/demo/pie-drilldown)
  - [scatter](https://www.highcharts.com/demo/scatter)
  - [bubble](https://www.highcharts.com/demo/bubble)
  - [bullet](https://www.highcharts.com/demo/bullet-graph)
  - [histogram](https://www.highcharts.com/demo/histogram)
  - [pyramid](https://www.highcharts.com/demo/pyramid)
  - [area](https://www.highcharts.com/demo/area-basic)
- StockChart:
  - [standard](https://www.highcharts.com/stock/demo/basic-line)
  - [columnrange](https://www.highcharts.com/stock/demo/columnrange)
- MapChart
  - [standard](https://www.highcharts.com/maps/demo/map-bubble)

I'd prefer to add support for more charts as needed rather than up front. So I've left out some fairly common charts and am very open to dropping a few others we may not need (eg histogram).

### How do we use color? 

Areas that use color:

- chart content:
  - dynamically pulled from gradient
- axis lines:
  - light utility gray
- axis ticks:
  - light utility gray
- plot band:
  - text: brand black
  - bg: transparent version of accent color?
  - bg hover/selection: accent color?
- plot line:
  - line: accent color
  - text: brand black
- tooltip:
  - bg: brand white
  - border: matches color of hovered data
  - text: brand black
- legend:
  - bg: brand white
  - border: brand black (only needed for floating legends)
  - text: brand black
- map (bg, borders, data overlay, null data, disabled, hover, selection)
  - borders: utility gray
  - hover: brand primary dark
  - selection: brand primary
  - data: chart colors array
  - bg: ____?
  - null data: ____?
  - disabled: ____?
- loading overlay:
  - bg: mostly transparent brand white
- marker:
  - bg: matches color of data
- zones:
  - bg: need array of colors that aren't identical to main chart colors..
- negative color (items below threshold):
  - utility gray

I think charts are usually too busy, so my current idea is colors pulled from a gradient based on our brand colors. We'd want the most distance between colors possible, so I would expect to pull colors based on how many data points the chart has. See an example what colors would be used by a charts with 1-12 data points:

![colors](https://user-images.githubusercontent.com/270193/39246833-af8f9b56-4865-11e8-91a7-16ba0e4c678b.png)

https://color-interpolation.stackblitz.io/

### What maps do we support?

I know we have mostly US customers, but I'm assuming if we are showing something like site visits we would need a world map?

Currently I'm planning on:

- USA
- North America
- World

A list of all offered maps: http://code.highcharts.com/mapdata/ We can also create/provide our own.

### Do we support chart drilldown?

- Is it supported on all chart types? (bar, map, etc)
- Not all charts will need it.. how will the user know if they can interact with a chart?

[Pie drilldown example](https://www.highcharts.com/demo/pie-drilldown)
[Column drilldown example](https://www.highcharts.com/demo/column-drilldown)

### Can users interact/select parts of the charts?

Currently hovering shows data under the cursor but the user cannot click on data points etc. Are there any use-cases where the user selects a data point and then can do something?

[Pie selection example](https://www.highcharts.com/demo/pie-basic)
[Line selection example](https://www.highcharts.com/demo/line-ajax)

### What shape markers?

Do we support more than one shape? If so, when is each shape used etc.

[Custom marker example](https://www.highcharts.com/demo/spline-symbols)

### How are numbers formatted?

- Decimal places, rounding, currency prefix, etc
- Is it different for various charts?

### How close (or far) can axis points be from one another?

Currently letting HighCharts make a best choice based on data.

### Are axis lengths rounded to the closest point?

Currently yes for line, no for all others.

### Do we support plot bands?

- How should the plot band label be aligned?

[Example plot band](https://www.highcharts.com/demo/spline-plot-bands)

### Do we support plot lines?

- How should the plot line label be aligned?

[Plotline example](https://www.highcharts.com/stock/demo/yaxis-plotlines)

### Do we support zones?

- What is the prefered dash style?
- Is more than one dash style needed?

[Zones example](https://www.highcharts.com/docs/chart-concepts/series#zones)

### Are legends used?

Currently yes. We can hide the legend and put labels on the data itself, but we lose the ability to allow the user to toggle datasets on/off.

- Shown by default or via interaction?
  - Currently shown by default.
- Where should the legend be positioned?
  - Currently centered bottom for simplicity. Floating legends depend on knowing where visual gaps will appear in your data. Also assuming possible filtering at top.
- Type styles for legend?
  - Roboto typeface
  - Brand black
- Hover styles for legend?
  - Brand primary
- Should they have a title?

[Example legend at bottom](https://www.highcharts.com/demo/spline-irregular-time)
[Example legend top left](https://www.highcharts.com/demo/line-ajax)
[Example floating legend](https://www.highcharts.com/demo/area-missing)

### Tooltips

- Do any tooltips have interactive content? (links etc)
  - Currently possible, but limited HTML support
- Does tooltip follow mouse or stay locked to data area?
  - Currently locked to minimize noise
- Are multi-point tooltips shared, separate or split?
  - Currently split for clarity except for pie charts which don't handle split well.
- Do we allow tooltip formatting? (headers, tables, links etc)

[Example split](https://www.highcharts.com/demo/area-stacked)
[Example separate](https://www.highcharts.com/demo/area-missing)
[Example shared](https://www.highcharts.com/demo/areaspline)

### Crosshairs

- Do we use show the axis crosshairs?
  - Currently we show both x and y crosshairs, except for maps and pie charts.

[Y crosshair example](https://www.highcharts.com/stock/demo/basic-line)

### Filtering

The 'stock' charts support built in filtering, do we want to allow/use this?

Pros:
  - built in
  - standard controls
  - timeline filter
Cons:
  - minimal or no style control
  - filter only affects chart so changing any other page content with the chart won't work
  - no customization for defined ranges

[Example stock filters](https://www.highcharts.com/stock/demo/basic-line)

### Can charts be exported?

- PNG, PDF, JGP, SVG, CSV, XLS

Currently planning on yes.

### When should we use which chart?

We should have some rules here.. (ie When dealing with a single set of data on two axis use.. etc)

### Do charts support zooming?

- All charts? Some charts? (note: `zoom` is different than drilldown)

Currently not planning on supporting. I see drilldown being usefull, but haven't seen anything where filters and drilldown won't suffice.

[Example zoom](https://www.highcharts.com/demo/arearange)

### Label positioning

Currently letting Highcharts decide based on labels. Will use 90 degree labels unless spacing doesn't allow. Then it will rotate the labels as needed up to 45 degrees.

### Do we support annotations?

Currently not planned.

[Example annotations](https://www.highcharts.com/demo/annotations)

### Component Name?

Originally this was a 'chart' component but that may be too narrow? If you hear 'chart' would you know that a map visualization would be included?

I feel that product or engineering should know that this encompasses all of our data visualization abilities..

Options:

- `<ts-chart format="bar" [data]="myData">`
- `<ts-data format="bar"[data]="myData">`
- `<ts-data-viz format="bar" [data]="myData">`
- `<ts-graph format="bar" [data]="myData">`
- `<ts-visualization format="bar" [data]="myData">`

Currently going with `<ts-chart>` as it seems to be the most descriptive yet short name.

**Comment by benjamincharity** [comment]
cc @Shelton @lildziner @dpeet first pass at guidelines and questions.

**Comment by benjamincharity** [comment]
A resource I've found useful in the past when determining how to best show different types of data:

![screen shot 2018-05-07 at 7 46 41 am](https://user-images.githubusercontent.com/270193/39700366-eb18532a-51ca-11e8-8774-75f69102fd4e.png)

**Comment by dpeet** [comment]
yo @benjamincharity this is amazing

**Comment by benjamincharity** [comment]
@Shelton beta version of charting is now out: https://terminus-ui-demos.stackblitz.io/components/chart
