### ISSUE TITLE
New Select/Autocomplete Functionality

### ISSUE THREAD

**Issue by dpeet** [GetTerminus/terminus-ui#847]
Issue to track development of new Select/Autocomplete Component

> We should also look into merging any search functionality into this. Then we can deprecate `TsSearch`

- [ ] Replace `TsSelect` (target 9.0)
- [ ] Deprecate `TsAutocomplete` (target 10.0)
- [ ] Deprecate `TsSearch` (target 10.0)
- https://sketch.cloud/s/xgx3J

---

### High-level feature set

- Works with ngModel
- Works with FormControl
- Floating label
- Single or multiple select
- Disabled
- Seed initial value (using form control or ngModel)
- Formatter for UI
- Formatter for model
- Ability to create a new item that wasn't originally in the list
- Events
- Categorized options
- Theme support
- Debounce search
- Query is only sent if unique
- Show error for duplicate selection
- Mark as touched if opened and closed with no selection
- Mark required if attr or form validation exists (`hasRequiredControl`)
- Validation message support
- Hint support
- Chips have delete button
- Token separators: `,`
- Individual option can be disabled
- Ability to clear single select (`x` on right like search component)
- Dropdown appears below input
  - Exception: If a value is selected, that value is vertically centered in the select when opened. If multiple values are selected, the first selection is centered vertically.
- Selects with many options by default show a single option that says 'load all options'
- Options or selections that are longer than the input should wrap so that all text is visible.
- Verify placeholder isn't used since it will duplicate the label.

#### API

```
- @Input theme: TsStyleThemeTypes
- @Input debounceDelay: number = 200
- @Input hint: string
- @Input label: string
- @Input multiple: boolean
- @Input showProgress: boolean
- @Input control: AbstractControl
- @Input inputName: string
- @Input options: any[]
- @Input disabled: boolean
- @Input minimumQueryLength: number
- @Input maxSelectionCount: number
- @Input optionFormat: Template
- @Input allowCreation: boolean
- @Input enableSearch: boolean
- @Output query (term: string)
- @Output openChange (isOpen: boolean)
- @Output change (selections: any[])
- @Output add (item: any)
- @Output loadAll (shouldLoad: boolean)
```

#### Opt grouping by data-structure

I don't prefer to force data-structures. Is it possible to determine sub-items based on a function (like model formatting etc)?

```javascript
// Example 1:
[
  {
    foo: 'bar',
  },
  {
    foo: 'baz',
    items: [{}, ...], // items will appear as a sub-group
  },
  {
    foo: 'bing',
    disabled: true,
  },
]
```

---

#395 should also be addressed during this ticket

**Comment by dpeet** [comment]
[Interaction Comp](https://select2.org/getting-started/basic-usage)

**Comment by benjamincharity** [comment]
On hold until core plans to integrate

**Comment by benjamincharity** [comment]
Reopened as epic #1025
