### ISSUE TITLE
Texting Overlap 

### ISSUE THREAD

**Issue by sunbuns** [GetTerminus/terminus-ui#849]
![image](https://user-images.githubusercontent.com/19916526/39480098-2d037322-4d35-11e8-8219-5b0afa55867a.png)

**Comment by sunbuns** [comment]
![image](https://user-images.githubusercontent.com/19916526/39480131-4a1bb410-4d35-11e8-81cc-39423cc54d8e.png)

**Comment by benjamincharity** [comment]
Tracked via #842
