### ISSUE TITLE
Icon: Investigate extra line when using check-circle

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#928]
Use `check-circle` icon:

![image](https://user-images.githubusercontent.com/270193/40925616-26cfa656-67e8-11e8-8f9b-d6bc497ba8ad.png)

**Comment by benjamincharity** [comment]
This may no longer be an issue - need to verify

**Comment by shani-terminus** [comment]
Use underscore instead of dash.

![screen shot 2019-02-27 at 2 05 02 pm](https://user-images.githubusercontent.com/44702601/53515904-0b917480-3a99-11e9-8162-b69e7d561642.png)
