### ISSUE TITLE
Look into scripting to auto-update the master Sketch file from component files

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#936]
https://www.youtube.com/watch?v=A-lNv6Szu3M

**Comment by dpeet** [comment]
@benjamincharity I finally had a chance to watch it.  It reminded me a lot of https://kactus.io/ which we just explored.  the big sticking point is visual diffs and managing conflicts, which abstract seems to do a little better

**Comment by benjamincharity** [comment]
Main reason I was looking into this approach was for an automated way to sync the sketch file with the actual code.

**Comment by benjamincharity** [comment]
Outdated. UX is looking at other sync methods.
